/**
 * API KEY EXAMPLE FILE
 *
 * This is a template. DO NOT edit this file directly.
 *
 * Instead:
 * 1. Run: npm run setup
 *    OR
 * 2. Copy this file to api-key.ts and add your key:
 *    cp src/config/api-key.example.ts src/config/api-key.ts
 *
 * Then edit api-key.ts with your OpenAI API key.
 */

export const OPENAI_API_KEY = '';
